FROM eclipse-temurin:21-jre-jammy

ARG PROFILE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_KEY
ARG JWT_SECRET
ARG RECEIPT_DATASOURCE_PG_URL
ARG RECEIPT_API_USER_DB_PASSWORD
ARG RECEIPT_DATASOURCE_DB_NAME
ARG S3_RECEIPT_ADMIN_BUCKET_NAME
ARG KOCES_PAY_TOKEN
ARG JWT_DOMAIN
ARG JWT_ISSUER
ARG RECEIPT_GATE_KOCES_PAY_URL

ENV TZ=Asia/Seoul
ENV KTOR_ENV=$PROFILE
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_KEY=$AWS_SECRET_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV RECEIPT_DATASOURCE_PG_URL=$RECEIPT_DATASOURCE_PG_URL
ENV RECEIPT_API_USER_DB_PASSWORD=$RECEIPT_API_USER_DB_PASSWORD
ENV RECEIPT_DATASOURCE_DB_NAME=$RECEIPT_DATASOURCE_DB_NAME
ENV S3_RECEIPT_ADMIN_BUCKET_NAME=$S3_RECEIPT_ADMIN_BUCKET_NAME
ENV KOCES_PAY_TOKEN=$KOCES_PAY_TOKEN
ENV JWT_DOMAIN=$JWT_DOMAIN
ENV JWT_ISSUER=$JWT_ISSUER
ENV RECEIPT_GATE_KOCES_PAY_URL=$RECEIPT_GATE_KOCES_PAY_URL

WORKDIR /app

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY build/libs/e-receipt-api-fat.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["sh","-c","java -DKTOR_ENV=${KTOR_ENV} -jar app.jar -config=application.conf"]